[build]
  bin               = "/usr/bin/true"
  cmd               = "make build-tw notify-templ-proxy"
  delay             = 1000
  exclude_dir       = ["docs", "testdata", "tmp", "vendor"]
  exclude_file      = ["assets/output.css", "screenshots.js"]
  exclude_regex     = ["_templ.go", "_test.go"]
  exclude_unchanged = false
  include_ext       = ["css", "go", "html", "js", "json", "tmpl", "tpl", "yaml"]
  stop_on_error     = true

[screen]
  clear_on_rebuild = false
