services:
  workout-tracker-assets:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: builder-frontend
    volumes:
      - asset-volume:/app/assets
      - ./views:/app/views
      - ./frontend/src:/app/frontend/src
    tty: true
  workout-tracker:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: builder-backend
    container_name: wt-app-dev
    restart: unless-stopped
    ports:
      # Host Port:Container Port
      - 8080:8080
    volumes:
      # Mount local directory for sqlite database
      - db-data:/data
      - asset-volume:/app/assets
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./vendor:/app/vendor
      - ./views:/app/views
      - ./translations:/app/translations
    environment:
      - APP_ENV=development
      - WT_DSN=/data/workout-tracker.db
      - WT_JWT_ENCRYPTION_KEY=dev-secret-key
volumes:
  asset-volume:
  db-data:
