// Code generated by generate-workout-types; DO NOT EDIT.
package database

// DistanceRecordTarget defines a target distance label and its size in meters.
type DistanceRecordTarget struct {
	Label          string
	TargetDistance float64
}

var defaultDistanceRecordTargets = map[WorkoutType][]DistanceRecordTarget{
	WorkoutTypeRunning: {
		{Label: "5 km", TargetDistance: 5000.0000},
		{Label: "10 km", TargetDistance: 10000.0000},
		{Label: "Half Marathon", TargetDistance: 21097.5000},
		{Label: "Marathon", TargetDistance: 42195.0000},
	},
	WorkoutTypeCycling: {
		{Label: "5 mi", TargetDistance: 8046.7200},
		{Label: "10 km", TargetDistance: 10000.0000},
		{Label: "10 mi", TargetDistance: 16093.4400},
		{Label: "20 km", TargetDistance: 20000.0000},
		{Label: "50 km", TargetDistance: 50000.0000},
		{Label: "50 mi", TargetDistance: 80467.2000},
		{Label: "75 km", TargetDistance: 75000.0000},
		{Label: "100 km", TargetDistance: 100000.0000},
		{Label: "100 mi", TargetDistance: 160934.4000},
	},
	WorkoutTypeECycling: {
		{Label: "5 mi", TargetDistance: 8046.7200},
		{Label: "10 km", TargetDistance: 10000.0000},
		{Label: "10 mi", TargetDistance: 16093.4400},
		{Label: "20 km", TargetDistance: 20000.0000},
		{Label: "50 km", TargetDistance: 50000.0000},
		{Label: "50 mi", TargetDistance: 80467.2000},
		{Label: "75 km", TargetDistance: 75000.0000},
		{Label: "100 km", TargetDistance: 100000.0000},
		{Label: "100 mi", TargetDistance: 160934.4000},
	},
}

func distanceRecordTargetsFor(wt WorkoutType) []DistanceRecordTarget {
	targets, ok := defaultDistanceRecordTargets[wt]
	if !ok {
		return nil
	}

	return targets
}
