/**
 * Icon providers configuration for ng-icons
 * This file provides all icons used in the application based on icon-map.ts
 */

import { provideIcons } from '@ng-icons/core';

// Font Awesome Solid Icons
import {
  faSolidArrowDownLong,
  faSolidArrowRightArrowLeft,
  faSolidArrowsLeftRight,
  faSolidArrowsRotate,
  faSolidArrowUpLong,
  faSolidBan,
  faSolidBars,
  faSolidBicycle,
  faSolidBookmark,
  faSolidCalculator,
  faSolidChartLine,
  faSolidChartSimple,
  faSolidChevronDown,
  faSolidChevronRight,
  faSolidChevronUp,
  faSolidCircleExclamation,
  faSolidCircleNotch,
  faSolidCirclePlus,
  faSolidCircleUser,
  faSolidClipboard,
  faSolidClipboardCheck,
  faSolidCompass,
  faSolidCrosshairs,
  faSolidDownload,
  faSolidDumbbell,
  faSolidEye,
  faSolidEyeSlash,
  faSolidFile,
  faSolidFire,
  faSolidGauge,
  faSolidGaugeHigh,
  faSolidGear,
  faSolidGlobe,
  faSolidGolfBallTee,
  faSolidHeartPulse,
  faSolidHorse,
  faSolidLanguage,
  faSolidLockOpen,
  faSolidMapLocationDot,
  faSolidMountain,
  faSolidPenToSquare,
  faSolidPersonHiking,
  faSolidPersonRunning,
  faSolidPersonSkating,
  faSolidPersonSkiing,
  faSolidPersonSnowboarding,
  faSolidPersonSwimming,
  faSolidPersonWalking,
  faSolidQuestion,
  faSolidQuoteLeft,
  faSolidRetweet,
  faSolidRightFromBracket,
  faSolidRightToBracket,
  faSolidRoad,
  faSolidRoute,
  faSolidRuler,
  faSolidRulerVertical,
  faSolidSailboat,
  faSolidShareFromSquare,
  faSolidSquareCheck,
  faSolidStopwatch,
  faSolidTag,
  faSolidTemperatureHigh,
  faSolidTrash,
  faSolidTrophy,
  faSolidUser,
  faSolidUserLock,
  faSolidUserPlus,
  faSolidUsers,
  faSolidWater,
  faSolidWeightHanging,
  faSolidXmark,
} from '@ng-icons/font-awesome/solid';

// Font Awesome Regular Icons
import {
  faCalendar,
  faCircleUser,
  faClock,
  faHourglass,
  faRectangleList,
} from '@ng-icons/font-awesome/regular';

// Ionicons
import { ionFootsteps, ionScale } from '@ng-icons/ionicons';

// Octicons
import { octMarkGithub } from '@ng-icons/octicons';

/**
 * Provider configuration for all icons used in the application
 * Import this in app.config.ts to make all icons available globally
 */
export const iconProviders = provideIcons({
  // Font Awesome Solid
  faSolidBars,
  faSolidBookmark,
  faSolidRoad,
  faSolidGauge,
  faSolidGaugeHigh,
  faSolidStopwatch,
  faSolidMountain,
  faSolidMapLocationDot,
  faSolidCalculator,
  faSolidWeightHanging,
  faSolidHeartPulse,
  faSolidTemperatureHigh,
  faSolidCompass,
  faSolidCrosshairs,
  faSolidTag,
  faSolidRulerVertical,
  faSolidChevronRight,
  faSolidCircleNotch,
  faSolidArrowRightArrowLeft,
  faSolidRuler,
  faSolidFile,
  faSolidArrowUpLong,
  faSolidArrowDownLong,
  faSolidChevronUp,
  faSolidChevronDown,
  faSolidLanguage,
  faSolidArrowsLeftRight,
  faSolidShareFromSquare,
  faSolidRetweet,
  faSolidPersonRunning,
  faSolidPersonWalking,
  faSolidPersonSwimming,
  faSolidPersonSkating,
  faSolidPersonSkiing,
  faSolidPersonSnowboarding,
  faSolidGolfBallTee,
  faSolidSailboat,
  faSolidPersonHiking,
  faSolidHorse,
  faSolidDumbbell,
  faSolidQuestion,
  faSolidChartLine,
  faSolidChartSimple,
  faSolidGear,
  faSolidCircleUser,
  faSolidUserPlus,
  faSolidBicycle,
  faSolidRoute,
  faSolidCirclePlus,
  faSolidFire,
  faSolidClipboardCheck,
  faSolidXmark,
  faSolidPenToSquare,
  faSolidArrowsRotate,
  faSolidTrash,
  faSolidQuoteLeft,
  faSolidUsers,
  faSolidRightToBracket,
  faSolidRightFromBracket,
  faSolidUser,
  faSolidEye,
  faSolidEyeSlash,
  faSolidClipboard,
  faSolidDownload,
  faSolidCircleExclamation,
  faSolidSquareCheck,
  faSolidUserLock,
  faSolidLockOpen,
  faSolidGlobe,
  faSolidWater,
  faSolidBan,
  faSolidTrophy,

  // Font Awesome Regular
  faClock,
  faCalendar,
  faHourglass,
  faRectangleList,
  faCircleUser,

  // Ionicons
  ionFootsteps,
  ionScale,

  // Octicons
  octMarkGithub,
});
